name: Flutter Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Check example directory structure
        run: |
          cd example
          echo "当前目录: $(pwd)"
          echo "目录内容:"
          ls -la
          echo "android目录内容:"
          ls -la android/ || echo "没有android目录"
      
      - name: Convert example to Flutter project if needed
        run: |
          cd example
          # 如果android目录不存在，则创建Flutter项目
          if [ ! -d "android" ]; then
            echo "创建Flutter项目结构..."
            flutter create --org com.example --project-name example_app .
          else
            echo "Android目录已存在，跳过创建项目"
          fi
      
      - name: Install dependencies
        run: |
          cd example
          flutter pub get
      
      - name: Clean build
        run: |
          cd example
          flutter clean
      
      - name: Build Android APK with verbose logging
        run: |
          cd example
          # 将详细日志输出到文件，同时也在控制台显示（但GitHub Actions可能会截断）
          flutter build apk --release --split-per-abi --verbose 2>&1 | tee build_log.txt
        continue-on-error: true
      
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: android-build-logs
          path: example/build_log.txt
      
      - name: Check build success
        if: failure()
        run: |
          echo "构建失败，请查看上传的构建日志"
          exit 1
      
      - name: Upload APK artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: example/build/app/outputs/flutter-apk/
      
      - name: Build Web app
        run: |
          cd example
          flutter build web --release
      
      - name: Upload Web build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: example/build/web/

  # 部署到 GitHub Pages (可选)
  deploy-web:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download web build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: example/build/web/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
