name: Flutter Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Check and prepare example directory
        run: |
          # 检查example目录是否存在
          if [ ! -d "example" ]; then
            echo "example目录不存在，创建example目录并初始化Flutter应用"
            flutter create --org com.example --project-name example_app example
          else
            echo "example目录存在"
            cd example
            # 检查是否有pubspec.yaml
            if [ ! -f "pubspec.yaml" ]; then
              echo "example目录中没有pubspec.yaml，初始化Flutter应用"
              cd ..
              flutter create --org com.example --project-name example_app example
            else
              echo "example目录中有pubspec.yaml"
              # 检查是否有lib/main.dart
              if [ ! -f "lib/main.dart" ]; then
                echo "example目录中没有lib/main.dart，创建默认的main.dart"
                mkdir -p lib
                cat > lib/main.dart << 'EOF'
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    home: Scaffold(
      body: Center(
        child: Text('Example App for SDK'),
      ),
    ),
  ));
}
EOF
              fi
            fi
          fi
      
      - name: Install dependencies in example
        run: |
          cd example
          flutter pub get
      
      - name: Build Android APK from example
        run: |
          cd example
          flutter build apk --release --split-per-abi
      
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: example/build/app/outputs/flutter-apk/
      
      - name: Build Web app from example
        run: |
          cd example
          flutter build web --release
      
      - name: Upload Web build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: example/build/web/