name: Flutter Build and Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Check example directory structure
        run: |
          cd example
          ls -la
      
      - name: Create Flutter project in example directory
        run: |
          cd example
          flutter create . --project-name example --org com.example
      
      - name: Install dependencies in example
        run: |
          cd example
          flutter pub get
      
      - name: Build Android APK
        run: |
          cd example
          flutter build apk --release --split-per-abi
      
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: example/build/app/outputs/flutter-apk/
      
      - name: Build Web app
        run: |
          cd example
          flutter build web --release
      
      - name: Upload Web build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: example/build/web/

  deploy-web:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download web build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: example/build/web/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
