name: Flutter Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # 分析和测试工作
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test

  # 构建 Android APK
  build-android:
    needs: analyze-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Install Flutter dependencies
        run: flutter pub get
      
      - name: Check Android environment
        run: flutter doctor -v
      
      - name: Build Android APK
        run: flutter build apk --release --split-per-abi
      
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/

  # 构建 Web 应用
  build-web:
    needs: analyze-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install Flutter dependencies
        run: flutter pub get
      
      - name: Build Web app
        run: flutter build web --release
      
      - name: Upload Web build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web/

  # 部署到 GitHub Pages (可选)
  deploy-web:
    needs: build-web
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download web build artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: build/web/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
